import type { ComponentDefinition, ComponentType } from '@/types';

export const COMPONENT_DEFINITIONS: ComponentDefinition[] = [
  // ─── Basic ────────────────────────────────────────────────────────────────
  {
    type: 'heading',
    category: 'basic',
    label: 'Heading',
    icon: 'Heading1',
    description: 'Title or section heading',
    defaultLayout: { width: 'auto', height: 'auto', padding: 0 },
    defaultContent: { title: 'Heading' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'text',
    category: 'basic',
    label: 'Text',
    icon: 'AlignLeft',
    description: 'Paragraph or body text',
    defaultLayout: { width: 'auto', height: 'auto', padding: 0 },
    defaultContent: { text: 'Body text goes here' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'button',
    category: 'basic',
    label: 'Button',
    icon: 'MousePointerClick',
    description: 'Interactive call-to-action button',
    defaultLayout: { width: 'auto', height: 40, padding: 8, borderRadius: 6 },
    defaultContent: { label: 'Button' },
    defaultSemantic: { role: 'primary-action' },
    canHaveChildren: false,
  },
  {
    type: 'image',
    category: 'basic',
    label: 'Image',
    icon: 'Image',
    description: 'Image or media placeholder',
    defaultLayout: { width: 300, height: 200, borderRadius: 8 },
    defaultContent: { alt: 'Image placeholder' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'avatar',
    category: 'basic',
    label: 'Avatar',
    icon: 'UserCircle',
    description: 'User avatar or profile image',
    defaultLayout: { width: 40, height: 40, borderRadius: 9999 },
    defaultContent: { alt: 'User avatar' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'badge',
    category: 'basic',
    label: 'Badge',
    icon: 'Tag',
    description: 'Status badge or label chip',
    defaultLayout: { width: 'auto', height: 'auto', padding: 4, borderRadius: 9999 },
    defaultContent: { label: 'Badge' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'divider',
    category: 'basic',
    label: 'Divider',
    icon: 'Minus',
    description: 'Horizontal rule separator',
    defaultLayout: { width: 300, height: 1 },
    defaultContent: {},
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'icon',
    category: 'basic',
    label: 'Icon',
    icon: 'Smile',
    description: 'Icon element',
    defaultLayout: { width: 24, height: 24 },
    defaultContent: { label: 'star' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'link',
    category: 'basic',
    label: 'Link',
    icon: 'Link',
    description: 'Hyperlink or text link',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: 'Click here', href: '#' },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },

  // ─── Form ─────────────────────────────────────────────────────────────────
  {
    type: 'input',
    category: 'form',
    label: 'Input',
    icon: 'TextCursorInput',
    description: 'Text input field',
    defaultLayout: { width: 280, height: 'auto', padding: 8, borderRadius: 6 },
    defaultContent: { label: 'Label', placeholder: 'Enter text...' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'textarea',
    category: 'form',
    label: 'Textarea',
    icon: 'AlignJustify',
    description: 'Multi-line text input',
    defaultLayout: { width: 280, height: 96, padding: 8, borderRadius: 6 },
    defaultContent: { label: 'Label', placeholder: 'Enter message...' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'select',
    category: 'form',
    label: 'Select',
    icon: 'ChevronDown',
    description: 'Dropdown select field',
    defaultLayout: { width: 280, height: 'auto', padding: 8, borderRadius: 6 },
    defaultContent: { label: 'Label', placeholder: 'Select option...' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'checkbox',
    category: 'form',
    label: 'Checkbox',
    icon: 'CheckSquare',
    description: 'Checkbox input',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: 'Checkbox label' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'radio',
    category: 'form',
    label: 'Radio',
    icon: 'CircleDot',
    description: 'Radio button group',
    defaultLayout: { width: 'auto', height: 'auto', gap: 8 },
    defaultContent: { label: 'Option 1' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'toggle',
    category: 'form',
    label: 'Toggle',
    icon: 'ToggleLeft',
    description: 'On/off switch toggle',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: 'Enable feature' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'slider',
    category: 'form',
    label: 'Slider',
    icon: 'SlidersHorizontal',
    description: 'Range slider input',
    defaultLayout: { width: 250, height: 'auto' },
    defaultContent: { label: 'Value' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },

  // ─── Feedback ─────────────────────────────────────────────────────────────
  {
    type: 'progress',
    category: 'feedback',
    label: 'Progress',
    icon: 'Activity',
    description: 'Progress bar indicator',
    defaultLayout: { width: 250, height: 8, borderRadius: 9999 },
    defaultContent: { label: '60' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'spinner',
    category: 'feedback',
    label: 'Spinner',
    icon: 'Loader2',
    description: 'Loading spinner',
    defaultLayout: { width: 32, height: 32 },
    defaultContent: {},
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'alert',
    category: 'feedback',
    label: 'Alert',
    icon: 'AlertCircle',
    description: 'Alert or notification banner',
    defaultLayout: { width: 'auto', height: 'auto', padding: 12, borderRadius: 8 },
    defaultContent: { title: 'Heads up!', text: 'This is an alert message.' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'tooltip',
    category: 'feedback',
    label: 'Tooltip',
    icon: 'MessageSquare',
    description: 'Tooltip popup label',
    defaultLayout: { width: 'auto', height: 'auto', padding: 6, borderRadius: 4 },
    defaultContent: { text: 'Tooltip text' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'tag',
    category: 'feedback',
    label: 'Tag / Chip',
    icon: 'Hash',
    description: 'Tag, chip or category label',
    defaultLayout: { width: 'auto', height: 'auto', padding: 6, borderRadius: 9999 },
    defaultContent: { label: 'tag' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },

  // ─── Navigation ───────────────────────────────────────────────────────────
  {
    type: 'tabs',
    category: 'navigation',
    label: 'Tabs',
    icon: 'LayoutPanelLeft',
    description: 'Tab navigation bar',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: 'Tab 1' },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },
  {
    type: 'breadcrumb',
    category: 'navigation',
    label: 'Breadcrumb',
    icon: 'ChevronRight',
    description: 'Breadcrumb navigation trail',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: 'Home / Page / Item' },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },
  {
    type: 'pagination',
    category: 'navigation',
    label: 'Pagination',
    icon: 'MoreHorizontal',
    description: 'Page number pagination controls',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { count: 5 },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },
  {
    type: 'stepper',
    category: 'navigation',
    label: 'Stepper',
    icon: 'GitCommitHorizontal',
    description: 'Multi-step wizard progress',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { count: 3 },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },

  // ─── Layout ───────────────────────────────────────────────────────────────
  {
    type: 'container',
    category: 'layout',
    label: 'Container',
    icon: 'Square',
    description: 'Generic container for grouping',
    defaultLayout: { width: 'auto', height: 'auto', padding: 16, gap: 8 },
    defaultContent: {},
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'row',
    category: 'layout',
    label: 'Row',
    icon: 'Rows3',
    description: 'Horizontal flex container (side-by-side)',
    defaultLayout: { width: 'auto', height: 'auto', gap: 8 },
    defaultContent: {},
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'column',
    category: 'layout',
    label: 'Column',
    icon: 'Columns3',
    description: 'Vertical flex container',
    defaultLayout: { width: 'auto', height: 'auto', gap: 8 },
    defaultContent: {},
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'grid',
    category: 'layout',
    label: 'Grid',
    icon: 'LayoutGrid',
    description: 'CSS grid container',
    defaultLayout: { width: 'auto', height: 200, gap: 16, padding: 16 },
    defaultContent: { count: 3 },
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'section',
    category: 'layout',
    label: 'Section',
    icon: 'LayoutTemplate',
    description: 'Page section with padding',
    defaultLayout: { width: '100%', height: 'auto', padding: 32 },
    defaultContent: {},
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'spacer',
    category: 'layout',
    label: 'Spacer',
    icon: 'MoveVertical',
    description: 'Flexible spacing element',
    defaultLayout: { width: '100%', height: 24 },
    defaultContent: {},
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },

  // ─── Blocks ───────────────────────────────────────────────────────────────
  {
    type: 'card',
    category: 'blocks',
    label: 'Card',
    icon: 'CreditCard',
    description: 'Content card with border',
    defaultLayout: { width: 'auto', height: 'auto', padding: 16, borderRadius: 12 },
    defaultContent: { title: 'Card Title' },
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'navbar',
    category: 'blocks',
    label: 'Navbar',
    icon: 'Navigation',
    description: 'Top navigation bar',
    defaultLayout: { width: '100%', height: 56, padding: 16 },
    defaultContent: { title: 'App Name' },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: true,
  },
  {
    type: 'footer',
    category: 'blocks',
    label: 'Footer',
    icon: 'PanelBottom',
    description: 'Page footer section',
    defaultLayout: { width: '100%', height: 'auto', padding: 32 },
    defaultContent: {},
    defaultSemantic: { role: 'footer' },
    canHaveChildren: true,
  },
  {
    type: 'hero',
    category: 'blocks',
    label: 'Hero',
    icon: 'Sparkles',
    description: 'Full-width hero section',
    defaultLayout: { width: '100%', height: 'auto', padding: 64 },
    defaultContent: { title: 'Hero Headline', subtitle: 'Supporting subtitle text' },
    defaultSemantic: { role: 'hero' },
    canHaveChildren: true,
  },
  {
    type: 'modal',
    category: 'blocks',
    label: 'Modal',
    icon: 'AppWindow',
    description: 'Dialog or modal overlay',
    defaultLayout: { width: 480, height: 'auto', padding: 24, borderRadius: 12 },
    defaultContent: { title: 'Modal Title' },
    defaultSemantic: { role: 'modal' },
    canHaveChildren: true,
  },
  {
    type: 'sidebar',
    category: 'blocks',
    label: 'Sidebar',
    icon: 'PanelLeft',
    description: 'Side navigation panel',
    defaultLayout: { width: 240, height: 'auto', padding: 16 },
    defaultContent: { title: 'Navigation' },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: true,
  },
  {
    type: 'table',
    category: 'blocks',
    label: 'Table',
    icon: 'Table',
    description: 'Data table with rows and columns',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { count: 4 },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'list',
    category: 'blocks',
    label: 'List',
    icon: 'List',
    description: 'Ordered or unordered list',
    defaultLayout: { width: 'auto', height: 'auto', gap: 8 },
    defaultContent: { count: 4 },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'form',
    category: 'blocks',
    label: 'Form',
    icon: 'ClipboardList',
    description: 'Form container with inputs',
    defaultLayout: { width: 'auto', height: 'auto', padding: 24, gap: 16, borderRadius: 12 },
    defaultContent: { title: 'Form', label: 'Submit' },
    defaultSemantic: { role: 'container' },
    canHaveChildren: true,
  },
  {
    type: 'video',
    category: 'blocks',
    label: 'Video',
    icon: 'Play',
    description: 'Video player placeholder',
    defaultLayout: { width: 400, height: 280, borderRadius: 8 },
    defaultContent: { alt: 'Video placeholder' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'chart',
    category: 'blocks',
    label: 'Chart',
    icon: 'BarChart3',
    description: 'Chart or graph placeholder',
    defaultLayout: { width: 350, height: 240, borderRadius: 8 },
    defaultContent: { title: 'Chart Title' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'stat',
    category: 'blocks',
    label: 'Stat Card',
    icon: 'TrendingUp',
    description: 'KPI / metric card with number and label',
    defaultLayout: { width: 'auto', height: 'auto', padding: 20, borderRadius: 12 },
    defaultContent: { title: '24,521', text: 'Total Users', label: '+12% vs last month' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'timeline',
    category: 'blocks',
    label: 'Timeline',
    icon: 'GitBranch',
    description: 'Vertical timeline of events or steps',
    defaultLayout: { width: 'auto', height: 'auto', gap: 16 },
    defaultContent: { count: 3 },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'accordion',
    category: 'blocks',
    label: 'Accordion',
    icon: 'ChevronDown',
    description: 'Expandable accordion / FAQ items',
    defaultLayout: { width: 350, height: 'auto' },
    defaultContent: { count: 3, title: 'Accordion Item' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'map',
    category: 'blocks',
    label: 'Map',
    icon: 'Map',
    description: 'Map or location placeholder',
    defaultLayout: { width: 350, height: 300, borderRadius: 12 },
    defaultContent: { alt: 'Map placeholder' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'banner',
    category: 'blocks',
    label: 'Banner',
    icon: 'Megaphone',
    description: 'Announcement or promotional banner',
    defaultLayout: { width: 'auto', height: 'auto', padding: 12 },
    defaultContent: { text: '🎉 Big sale — 30% off everything today!', label: 'Shop now' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'bottom-nav',
    category: 'blocks',
    label: 'Bottom Nav',
    icon: 'PanelBottom',
    description: 'Mobile bottom navigation bar',
    defaultLayout: { width: '100%', height: 56 },
    defaultContent: { count: 4 },
    defaultSemantic: { role: 'navigation' },
    canHaveChildren: false,
  },
  // ─── Basic (extra) ────────────────────────────────────────────────────────
  {
    type: 'rating',
    category: 'feedback',
    label: 'Rating',
    icon: 'Star',
    description: 'Star rating widget',
    defaultLayout: { width: 'auto', height: 'auto' },
    defaultContent: { label: '4.5', text: '(128 reviews)' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'skeleton',
    category: 'feedback',
    label: 'Skeleton',
    icon: 'Square',
    description: 'Loading skeleton placeholder',
    defaultLayout: { width: 300, height: 80, borderRadius: 8 },
    defaultContent: {},
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  {
    type: 'toast',
    category: 'feedback',
    label: 'Toast',
    icon: 'Bell',
    description: 'Toast / snackbar notification',
    defaultLayout: { width: 320, height: 'auto', padding: 16, borderRadius: 12 },
    defaultContent: { title: 'Success!', text: 'Your changes have been saved.' },
    defaultSemantic: { role: 'display' },
    canHaveChildren: false,
  },
  // ─── Form (extra) ─────────────────────────────────────────────────────────
  {
    type: 'search',
    category: 'form',
    label: 'Search',
    icon: 'Search',
    description: 'Search input with icon',
    defaultLayout: { width: 300, height: 'auto', padding: 8, borderRadius: 9999 },
    defaultContent: { placeholder: 'Search...' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'date-picker',
    category: 'form',
    label: 'Date Picker',
    icon: 'Calendar',
    description: 'Date selection input',
    defaultLayout: { width: 280, height: 'auto', padding: 8, borderRadius: 6 },
    defaultContent: { label: 'Date', placeholder: 'Pick a date' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
  {
    type: 'file-upload',
    category: 'form',
    label: 'File Upload',
    icon: 'Upload',
    description: 'File upload dropzone',
    defaultLayout: { width: 350, height: 120, borderRadius: 12 },
    defaultContent: { text: 'Drop files here or click to upload', label: 'Browse files' },
    defaultSemantic: { role: 'form-field' },
    canHaveChildren: false,
  },
];

export const COMPONENT_MAP = new Map<ComponentType, ComponentDefinition>(
  COMPONENT_DEFINITIONS.map((d) => [d.type, d])
);

export const COMPONENT_CATEGORIES = {
  basic: COMPONENT_DEFINITIONS.filter((d) => d.category === 'basic'),
  form: COMPONENT_DEFINITIONS.filter((d) => d.category === 'form'),
  feedback: COMPONENT_DEFINITIONS.filter((d) => d.category === 'feedback'),
  navigation: COMPONENT_DEFINITIONS.filter((d) => d.category === 'navigation'),
  layout: COMPONENT_DEFINITIONS.filter((d) => d.category === 'layout'),
  blocks: COMPONENT_DEFINITIONS.filter((d) => d.category === 'blocks'),
};

export function getComponentDefinition(type: ComponentType): ComponentDefinition | undefined {
  return COMPONENT_MAP.get(type);
}
